### ISSUE TITLE
Left shift is being recognized as heredoc

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-shell-syntax#93]
## The code with a problem is:
```sh
#! /bin/bash

i=$(( 1 + 2))
i=$(( 1 << 2 ))
i=$((1 << 2))
i=$(( 1 + 2 ))
i=$((i<<2))
```

## It looks like:
![image](https://github.com/user-attachments/assets/7493efc2-55f7-4c28-b1fc-cd38c2cc38d4)

The scopes:
```
keyword.operator.heredoc.shell
meta.argument.shell
meta.statement.command.shell
meta.statement.shell
meta.parenthese.group.shell
meta.scope.subshell
meta.expression.assignment.shell
source.shell
```

## It should look like:
After the unexpected `heredoc` scope, the following lines end up with a heredoc scope, when instead they should be colored similarly to line 3. 

Originally from @skyp0714  in https://github.com/microsoft/vscode/issues/215908

**Comment by sonic2kk** [comment]
Facing this exact issue as well. Seems other editors have the exact same issue. When searching, I found numerous reports of this for Vim, and I am also experiencing this with the Kate editor.

Is there a workaround in the meantime? Is there a comment I can put somewhere to temporarily correct the highlighting? I maintain a large Bash script and this is going to cause broken highlighting for a few thousand lines :sweat_smile:

**Comment by skyp0714** [comment]
There is a workaround using the power operator (**). Devide or multiply
2**(shift num) inside the arithmetic operator.

E.g)$(( a << 3 ))  to   $(( a *(2**3) ))

**Comment by jeff-hykin** [comment]
should be fixed on v1.10.0!

**Comment by alexr00** [comment]
@jeff-hykin is this one that you plan to port to `master`?

**Comment by jeff-hykin** [comment]
> @jeff-hykin is this one that you plan to port to `master`?

Yes, thanks for reminding me

**Comment by StrangeRanger** [comment]
This extensions isn't directly built into VSCode, is it? If not, then closing the VSCode issues regarding this problem, doesn't make a whole lot of sense.

**Comment by friendly-bits** [comment]
This is still broken when the left-shift is preceded with an expression in parentheses:

`e=$(( (c) << 8 ))` turns everything after it into a string.

![image](https://github.com/user-attachments/assets/29350e73-0393-4771-be7e-2968b3025e14)

**Comment by CalebJamesStevens** [comment]
I'm still seeing this issue in 1.10
<img width="694" alt="Screenshot 2024-12-13 at 2 19 01 PM" src="https://github.com/user-attachments/assets/0a9f08ba-b0f7-4632-a686-b60d6cbcbdba" />

**Comment by kapa2512** [comment]
Found a workaround for this issue. Rather than using `i=$(( 1 << 2 ))` use `i=$(( ((0) | 1 << 2) ))`. Mathematically it is same thing, we 'OR' the expression with 0, which doesn't change the result but fix the highlighting issue.

**Comment by starball5** [comment]
Apologies for hijacking(?), but @alexr00 in your comment https://github.com/microsoft/vscode/issues/227068#issuecomment-2325163517, just for my curiosity, can you explain what license change blocks VS Code from getting the fix for this? My very very naive look at https://github.com/jeff-hykin/better-shell-syntax/commits/master/LICENSE doesn't help.

**Comment by RedCMD** [comment]
that would have been a confusion with the CPP grammar license 
which did change at some point 
https://github.com/jeff-hykin/better-cpp-syntax/commits/master/LICENSE

VSCode is update to date with this repo

**Comment by roussak** [comment]
Looks like this baby-bug feels OK and grows day-by-day… By the way, how did the recent birthday pass? Did you blow out the candles?
